name: flutter_image_converters
description: "A Flutter image converter and resizer with multi-language support"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_flavorizr: ^2.4.1
  provider: ^6.1.2
  image_picker: ^1.0.7
  image: ^4.1.7
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

  # Enable generation of localization files
  generate: true
